remote_theme: yous/whiteglass
title: Gabriel Mancino-Ball.
description: Mathematics Graduate Student.

url: "https://gmancino.github.io/"
baseurl: "/homepage"

markdown: kramdown
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6
